tap "homebrew/cask-fonts"	#	test 더 필요
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
#tap "homebrew/nodejs"
tap "homebrew/neovim"
#tap "mongodb/brew"

brew "ffmpeg"
brew "git"
brew "git-lfs"
brew "lsd"
brew "maven"
brew "neovim"
brew "node"
brew "p7zip"
brew "sbt"
#brew "tcl-tk"
#brew "zsh"	#	Catalina는 default zsh
brew "zsh-completions"
brew "mas"
#brew "mongodb/brew/mongodb-community"

cask "anaconda"
#cask "dbeaver-community"
#cask "font-hack-nerd-font"	#	failed
cask "iterm2"
cask "keepingyouawake"
#cask "powershell"
#cask "visual-studio-code"
cask "google-chrome"
cask "firefox"
cask "appcleaner"
cask "spectacle"
cask "dropbox"
#cask "onedrive"
cask "jetbrains-toolbox"
cask "docker-toolbox"
mas "Xcode", id: 497799835
mas "Calendar", id: 415181149
mas "LINE", id: 539883307
mas "KakaoTalk", id: 869223134
#mas "Slack", id: 803453959
